import{a as L,S as w,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))s(r);new MutationObserver(r=>{for(const a of r)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function t(r){const a={};return r.integrity&&(a.integrity=r.integrity),r.referrerPolicy&&(a.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?a.credentials="include":r.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(r){if(r.ep)return;r.ep=!0;const a=t(r);fetch(r.href,a)}})();const S="https://pixabay.com/api/",v="52812196-5a943dca1ddd7edd2406579c3";async function m(e,o=1){try{return(await L.get(S,{params:{key:v,q:e,page:o,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}catch(t){throw new Error(t.message)}}const b=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(e){const o=document.querySelector(".gallery"),t=e.map(s=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s.largeImageURL}">
          <img src="${s.webformatURL}" alt="${s.tags}" />
          <div class="info">
            <p><span class="info-title">Likes:</span> ${s.likes}</p>
            <p><span class="info-title">Views:</span> ${s.views}</p>
            <p><span class="info-title">Comments:</span> ${s.comments}</p>
            <p><span class="info-title">Downloads:</span> ${s.downloads}</p>
          </div>
        </a>
      </li>
    `).join("");o.insertAdjacentHTML("beforeend",t),b.refresh()}function q(){const e=document.querySelector(".gallery");e.innerHTML=""}function g(){document.querySelector(".loader").classList.add("visible")}function i(){document.querySelector(".loader").classList.remove("visible")}function f(){document.querySelector(".loadmore").classList.add("visible")}function l(){document.querySelector(".loadmore").classList.remove("visible")}const h=document.querySelector(".form"),M=h.querySelector('input[name="search-text"]'),P=document.querySelector(".loadmore");let u="",c=1,p=0;l();h.addEventListener("submit",async e=>{e.preventDefault();const o=M.value.trim();if(!o){n.error({title:"Error",message:"Please enter a search term!",position:"topRight"});return}u=o,c=1,q(),l(),g();try{const t=await m(u,c);if(i(),t.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}p=t.totalHits,y(t.hits),t.hits.length<p&&f()}catch(t){i(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}});P.addEventListener("click",async()=>{c+=1,l(),g();try{const e=await m(u,c);i(),y(e.hits);const t=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=p?(l(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):f()}catch(e){i(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}});
//# sourceMappingURL=index.js.map
